### ISSUE TITLE
Were you able to replicate the DLFix artefact?

### ISSUE THREAD

**Issue by nashid** [kwz219/NPR4J#1]
Do you plan to add the DLFix artefact?

Paper: DLFix: Context-based Code Transformation Learning for Automated Program Repair, ICSE'20
Artefact: https://github.com/ICSE-2019-AUTOFIX/ICSE-2019-AUTOFIX

**Comment by kwz219** [comment]
> Do you plan to add the DLFix artefact?
> 
> Paper: DLFix: Context-based Code Transformation Learning for Automated Program Repair, ICSE'20 Artefact: https://github.com/ICSE-2019-AUTOFIX/ICSE-2019-AUTOFIX

@nashid I failed to run their source codes.
