### ISSUE TITLE
Do you plan to add support for the CURE artefact?

### ISSUE THREAD

**Issue by nashid** [kwz219/NPR4J#2]
The authors of CURE made the artefact available. I am curious to know whether you plan to add the CURE artefact?  If yes, then do you have a tentative timeline when the support for CURE would be available?

Paper: CURE: Code-Aware Neural Machine Translation for Automatic Program Repair, ICSE'21
Artefact: https://github.com/lin-tan/CURE

**Comment by kwz219** [comment]
> The authors of CURE made the artefact available. I am curious to know whether you plan to add the CURE artefact? If yes, then do you have a tentative timeline when the support for CURE would be available?
> 
> Paper: CURE: Code-Aware Neural Machine Translation for Automatic Program Repair, ICSE'21 Artefact: https://github.com/lin-tan/CURE

@nashid Currently, I have no plan to add CURE. Considering add other artefacts to my repository is a time-consuming task, I have no regular plan to add all Neural Program Repair tools. For future updates, I may only consider the latest and SOTA NPR tools that have been evaluated on Defects4J.
