### ISSUE TITLE
Were you able to replicate the DEAR artefact?

### ISSUE THREAD

**Issue by nashid** [kwz219/NPR4J#4]
Were you able to replicate the DEAR artefact? 

Paper: DEAR: A Novel Deep Learning-based Approach for Automated Program Repair
Artefact: https://github.com/AutomatedProgramRepair-2021/dear-auto-fix

**Comment by kwz219** [comment]
> Were you able to replicate the DEAR artefact?
> 
> Paper: DEAR: A Novel Deep Learning-based Approach for Automated Program Repair Artefact: https://github.com/AutomatedProgramRepair-2021/dear-auto-fix

@nashid 
I failed to execute their source codes.

**Comment by nashid** [comment]
@kwz219 same here. I was unable to execute their code.
