### ISSUE TITLE
question  when training coconut

### ISSUE THREAD

**Issue by chongchongL** [kwz219/NPR4J#9]
![1688956740813](https://github.com/kwz219/NPR4J/assets/61173897/28d2369e-2d36-4014-96d7-9d38c3ee3fdc)

Hello, I have a question. When training coconut, I didn't find the --use-context option required in fairseq training. Did I miss something? I couldn't detect the presence of a context encoder in the code.

**Comment by kwz219** [comment]
@chongchongL 
the position of f-conv context encoder: fairseq/fairseq/models/fconv.py
and the use-context option is also used to load a contextual dataset at: fairseq/fairseq/tasks/translation.py

**Comment by chongchongL** [comment]
Thank you very mulch!
